### ISSUE TITLE
Devhub Issue: How to request a new OpenShift project. Link to Slack#requests needs to be updated

### ISSUE THREAD

**Issue by kelpisland** [BCDevOps/openshift-wiki#12]
> path: (do not delete) https://github.com/BCDevOps/openshift-wiki/blob/master/docs/OCP/StartingANewProject.md
 > (do not delete) devhub page: https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-a-new-OpenShift-project.

## Devhub Content Issue
The link to their requests channel points to Slack, there are probably more that need to updated to Rocket chat as well.

**Comment by sheaphillips** [comment]
fixed in #14
