### ISSUE TITLE
Devhub Issue: How to request new user access to OpenShift change slack links to rocket chat

### ISSUE THREAD

**Issue by kelpisland** [BCDevOps/openshift-wiki#15]
> path: (do not delete) https://github.com/BCDevOps/openshift-wiki/blob/master/docs/OCP/RequestUserAccess.md
 > (do not delete) devhub page: https://developer.gov.bc.ca/Getting-Started-on-the-DevOps-Platform/How-to-request-new-user-access-to-OpenShift

## Devhub Content Issue
links point to pathfinder Slack - need to be update to Rocket.Chat

**Comment by ShellyXueHan** [comment]
@kelpisland solved in pr #14 waiting for Shea for pr review.

**Comment by sheaphillips** [comment]
fixed in #14.
