### ISSUE TITLE
Devhub Issue: SSO Realm Creation Slack...

### ISSUE THREAD

**Issue by kelpisland** [BCDevOps/openshift-wiki#16]
> path: (do not delete) https://github.com/BCDevOps/openshift-wiki/blob/master/docs/OCP/RequestSSORealm.md
 > (do not delete) devhub page: https://developer.gov.bc.ca/Authentication-and-Authorization/SSO-Realm-Creation

## Devhub Content Issue
update slack reference to Rocket

**Comment by ShellyXueHan** [comment]
@kelpisland solved in pr #14 waiting for Shea for pr review.

**Comment by sheaphillips** [comment]
fixed thanks to @ShellyXueHan
