### ISSUE TITLE
Devhub Issue: How to Request New User Access to OpenShift [qjtfov]

### ISSUE THREAD

**Issue by csherman-gov** [BCDevOps/openshift-wiki#40]
> path: (do not delete) https://github.com/BCDevOps/openshift-wiki/blob/master/docs/OCP/RequestUserAccess.md
 > (do not delete) devhub page: /How-to-Request-New-User-Access-to-OpenShift

## Devhub Content Issue

Full name: Joseph Jin
- GitHub ID: josephBelmar
- Email address: joseph.jin@belmar.ca
- Organization: Belmar
- Project role: Full-stack Developer
- OpenShift projects: qjtfov - all environments

Full name: Arthur Newman
- GitHub ID: arthur-newman-belmar
- Email address: arthur.newman@belmar.ca
- Organization: Belmar
- Project role: Full-stack Developer
- OpenShift projects: qjtfov - all environments

Full name: Ryan Draper
- GitHub ID: r-draper-pwc
- Email address: ryan.w.draper@pwc.com
- Organization: PWC
- Project role: Admin, Full-stack Developer
- OpenShift projects: qjtfov - all environments

**Comment by jefkel** [comment]
This is not the correct Repository for access request issues, see https://github.com/BCDevOps/devops-requests repo instead.
