### ISSUE TITLE
Devhub Issue: BC Government SSO Service Definition [short description here]

### ISSUE THREAD

**Issue by vonfoovonbar** [BCDevOps/openshift-wiki#41]
> path: (do not delete) https://github.com/BCDevOps/openshift-wiki/blob/master/docs/RH-SSO/ServiceDefinition.md
 > (do not delete) devhub page: undefined

## Devhub Content Issue

Could not access BC Dev Exchange RocketChat - https://chat.pathfinder.gov.bc.ca/channel/devops-alerts -- via my GitHub account. Message received: Fail to connect to KeyCloak, please refresh!

**Comment by jefkel** [comment]
This is not a documentation content issue.
