### ISSUE TITLE
Devhub Issue: Requesting a SSO Realm to be created for and agile tool being developed called GLADIS.  Requested by Kimberly Adamec kimberly.adamec@gov.bc.ca

### ISSUE THREAD

**Issue by KADAMEC** [BCDevOps/openshift-wiki#44]
We are developing an agile tool called GLADIS and need single sign on.  We were advised by Clecio Varjao that a realm was required.

> path: (do not delete) https://github.com/BCDevOps/openshift-wiki/blob/master/docs/RH-SSO/RequestSSORealm.md
 > (do not delete) devhub page: /Requesting-a-SSO-Realm-to-be-created

**Comment by ShellyXueHan** [comment]
request captured in https://github.com/BCDevOps/devops-requests closing.
