### ISSUE TITLE
Devhub Issue: BC Government SSO Service Definition [short description here]

### ISSUE THREAD

**Issue by kelpisland** [BCDevOps/openshift-wiki#45]
> path: (do not delete) https://github.com/BCDevOps/openshift-wiki/blob/master/docs/RH-SSO/ServiceDefinition.md
 > (do not delete) devhub page: /BC-Government-SSO-Service-Definition

## Devhub Content Issue

The links to request a new realm point to rocket chat - need to update to devops-requests

**Comment by ShellyXueHan** [comment]
docs updated.
