### ISSUE TITLE
Devhub Issue: Requesting a SSO Realm to be created [add tags]

### ISSUE THREAD

**Issue by patricksimonian** [BCDevOps/openshift-wiki#50]
> path: (do not delete) https://github.com/BCDevOps/openshift-wiki/blob/master/docs/RH-SSO/RequestSSORealm.md
 > (do not delete) devhub page: https://developer.gov.bc.ca/Authentication-and-Authorization/Requesting-a-SSO-Realm-to-be-created

## Devhub Content Issue

this document should add tags as frontmattter to improve searchability

```yaml
tags:
- keycloak
- realm
- client
- authentication
- idir
- bceid
```

**Comment by ShellyXueHan** [comment]
added.
