### ISSUE TITLE
Devhub Issue: BC Government SSO Service Definition [Corporate PIA complete]

### ISSUE THREAD

**Issue by kelpisland** [BCDevOps/openshift-wiki#51]
> path: (do not delete) https://github.com/BCDevOps/openshift-wiki/blob/master/docs/RH-SSO/ServiceDefinition.md
 > (do not delete) devhub page: /BC-Government-SSO-Service-Definition

## Devhub Content Issue

Text to add:
The corporate Privacy Impact Assessment is now completed and signed off. This means basic deployments can refer to the corporate PIA avoiding re-work. Teams must still detail in their program PIA how they are using identity providers in their application context.

**Comment by ShellyXueHan** [comment]
added.
